name: Generate changelog and plugin archive for new release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Simple conventional changelog
        uses: lstocchi/simple-conventional-changelog@13071c09073f5deddf03d44d9af6a8b0f81ef227 #0.0.11
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          current-tag: ${{ steps.get_version.outputs.VERSION }}
          types-mapping: 'feat:Features,fix:Bug Fixes,docs:Documentation,refactor:Refactoring,build:Builds,chore:Other'
          scopes-mapping: 'UI:UI,Hub:Hub'
      - run: |
          echo '${{ steps.changelog.outputs.changelog }}'
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLUGIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          gh release create ${PLUGIN_VERSION} \
            --title "${PLUGIN_VERSION}" \
            --notes "$(cat << 'EOM'
          ${{ steps.changelog.outputs.changelog }}
          EOM
          )"
      - name: Attach zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${PLUGIN_VERSION} ./build/distributions/*

